### PR TITLE
Add "Sales Suspension" feature

### LINKED ISSUE #781: Option to turn off the shop (holidays, ...)
What about adding a way to turn off the e-commerce?

I'd add these options:

- [ ] Disable e-commerce
  - [ ] from [date/time]
  - [ ] until [date/time]
- Rich text message to be displayed to site visitors

If:
1. "disable e-commerce" is turned on
2. and "from" is empty or a date/time in the past
3. and "to" is empty or a date/time in the future

Then the checkout would be disabled.
Also, in the `/checkout` and  `/cart` pages we could display (if set) the configured rich text message.

This would be very helpful for example in case of holidays, as well as in any case when products can't be shipped for some days.

We could also add a new block type that doesn't output anything if the e-commerce is active, but displays the rich text message if the e-commerce is disabled (for example, we could add that block to the homepage, or in a global area so that it's displayed in every page).

If that's ok, I can of course submit a pull request with these features.

### PR DESCRIPTION
**Pull request by mlocati**
Close #781

### CODE REVIEW

**Comment by Mesuva** [comment]
I've merged this and I'm having a look.

I really like this idea, the only pause I have is that there already is a similar (but simpler) feature under 'Cart and Checkout', where you can put it into 'Catalog Mode'.

They serve _slightly_ different purposes though (and yours is much more featured), so I'm just thinking through whether the features should be combined

**Comment by mlocati** [comment]
Yep, they both turn off selling items. Here's what we can do:

1. in the upgrade method, check if we are upgrading from a version older than the one that introduces this new feature: in this case, set the `community_store.salesSuspension.suspend` configuration key to the value of `community_store.shoppingDisabled`
2. remove the select that contains "Disabled (Catalog Mode)" in the "Cart and Checkout" section
3. in the new "Sales Suspension", we can:
   1. change the select, so that it presents these options:
       - Sales are active (pre-selected if `community_store.salesSuspension.suspend` is false)
       - Sales are disabled (catalog mode) (pre-selected if `community_store.salesSuspension.suspend` is true and start/end dates are both null)
       - Sales are temporarily disabled (pre-selected otherwise)
   2. if the first or the second option are selected, we don't display the date/time pickers for start/end dates
   3. when saving: `community_store.salesSuspension.suspend` is false if the first option is selected, true otherwise

**Comment by mlocati** [comment]
If that's ok for you, I can of course submit a PR with these changes

**Comment by Mesuva** [comment]
Of course, all your help here is _immensely_ appreciated. 

I agree with the approach you've outlined.

**Pull request merged**
